- .idea/inspectionProfiles/Project_Default.xml
- .idea/vcs.xml
- README.md
- app/admin.py
- app/models.py
- reboot/settings.py
Changed the verified field to a boolean
@leesw98
> New pull request with quick fix

- app/models.py
> Added donation id returned for both donor and donation

- app/admin.py
- app/models.py
- app/urls.py
- app/views.py
issue #17  and #18.
Added a verification field that changes based on the AND of the item and donation verification fields. 
Added actions to verify/ un-verify fields in item and donations admin panel.
> Omar branch

- .travis.yml
- README.md
- requirements.txt
- test_sample.py
Closes #23 
Doesn't actually add any testing. It's the setup for future tests.
> Added travis.yml

- app/admin.py
fixing the issue relating to database and view, #32, #35, #34
> Vincent branch

- app/models.py
- app/utils.py
**Related Issue:**
- Closes #43 
**Changes:**
- Added Customer Ref. field
**TODO:**
- `git merge master` and utilize customer ref.
> Closes #43: Added Customer Ref. field

- app/tasks.py
- app/templates/app/CSVworked.html
> Quick fix for CSV parser refactor bug; Refactored CSVworked.html

- app/models.py
> Serialization

- README.md
- hooks/pre-commit
Changed pre-commit to be executable
> Further changes to pre-commit hook

- app/urls.py
- app/views.py
**Hold off merging until serialization is complete.**
- Added an endpoint at `/api/autocomplete`
Closes #65
> Issue 65 - Added an autocomplete endpoint returning JSON object

- app/static/admin/css/base.css
Made all items' sections' length to be the same.
> force all items' width to be the same

- app/models.py
- app/views/model_view.py
>  Fixed PUT and DELETE requestes and added better error checks.

- app/static/admin/css/responsive.css
- app/templates/admin/base.html
- app/templates/admin/base_site.html
- app/templates/admin/index.html
- app/templates/app/PollState.html
- app/templates/app/analytics.html
- app/templates/app/form.html
- app/views/model_view.py
- app/views/views.py
> Add breadcrumbs and navigations to admin view

- app/admin.py
> verified check

- app/models.py
- app/urls.py
- app/views/data_view.py
> Data Visualization/Analytics API endpoint

- app/worker/parser.py
remove the white space of different variables in the csv file
> Simple whitespace remove

- app/models.py
- app/static/admin/js/pages/gen_form/model/donation.js
- app/views/model_view.py
gen-tax_receipt_no method added in model.py & model_view.py
save(self) added in model.py
closes #128
> gen-tax_receipt_no method added in model.py & model_view.py

- app/templates/app/PollState.html
> Small undefined% bug

- app/static/admin/css/base.css
- app/static/admin/css/forms.css
> Donation hover effect

- app/admin.py
- app/migrations/0001_initial.py
- app/models.py
- app/templates/pdf/receipt.html
- app/views/data_view.py
- app/worker/generate_pdf.py
- app/worker/parser.py
Updated like following:
```
Donation: donor_id => donor
Item: tax_receipt_no => donation
```
> Updated field names in models and other files accordingly

- Makefile
- reboot/celery.py
> fix: Celery polling async result rejects

- reboot/celery.py
> set Celery backend url

- Makefile
- app/templates/admin/base_site.html
- app/templates/app/form.html
> fix duplicate calender option

- app/admin.py
- reboot/settings.py
- requirements.txt
> daterange filter

- app/admin.py
> Set pagination size to 25

- Makefile
- app/constants/perm_list.py
- app/management/commands/creategroups.py
Not adding superadmin as `superuser status` should be set per user
Closes #244
> feat: permission groups

- app/admin.py
> feat: Reorder some Item fields for better usage

- reboot/settings.py
- requirements.txt
> fix: django Permission table integrity error

- app/models/donation.py
- app/worker/tasks/importers/webform_data_importer.py
> fix: Donation pk generation edge cases

- app/admin.py
- app/constants/str.py
Closes https://github.com/CodeTheChangeUBC/reBOOT/issues/279
Related to https://github.com/CodeTheChangeUBC/reBOOT/issues/278
> feat: tax receipt revamp policy

- app/worker/tasks/create_receipt.py
> feat: tax receipt revamp counter clarification

- app/models/item.py
- app/templates/pdf/receipt.html
- runtime.txt
- static/admin/css/receipt.css
> feat: tax receipt particulars character limit

- app/admin.py
- app/views/views.py
- app/worker/tasks/exporter.py
- requirements.txt
Added a donation list page CSV export action feature
> feat: donation csv export

- app/utils/files.py
> feat: change encoding from latin-1 to utf-8

- app/test_admin.py
This PR adds test cases for `DonorAdmin` and `DonationAdmin`. The tests can be executed as follows:
1. `make env`
2. `make test`
> Add Donor Admin, Donation Admin Test Cases

- runtime.txt
This pull request fixes `runtime.txt`, as it doesn't support comments 😅
> Fix runtime.txt
